(()=>{'use strict';
const C={cat:27,portal:'transgaz64.bitrix24.ru',f:{addr:'UF_CRM_1716883559988',obj:'UF_CRM_DEAL_VDGO_OBJECT_URL',tech:'UF_CRM_1775823185',visit:'UF_CRM_1775823358',work:'UF_CRM_1775824643',nextTo:'UF_CRM_1775944515',result:'UF_CRM_1775944863',comment:'UF_CRM_1775945003',action:'UF_CRM_1775945295',nextContact:'UF_CRM_1775945348',done:'UF_CRM_1775946621'},s:{new:'C27:NEW',planned:'C27:PLANNED_TO',callback:'C27:CALLBACK',no1:'C27:UC_JQUBJU',no3:'C27:NOANSWER',legal:'C27:LEGAL',manual:'C27:MANUAL',agreed:'C27:UC_40ONW8',won:'C27:WON',lose:'C27:LOSE'},e:{visit:'10329',callback:'10335',completed:'10307',yes:'10359',emergency:'10241'}};
const S={mode:'loading',domain:C.portal,deals:[],contacts:new Map(),users:new Map(),stages:new Map(),selected:null,quick:'open',kpi:null,busy:false};
const $=id=>document.getElementById(id),E={};
document.addEventListener('DOMContentLoaded',()=>{['connectionBadge','refreshBtn','installBtn','searchInput','stageFilter','managerFilter','workTypeFilter','newDealBtn','kpiToday','kpiOverdue','kpiNoanswer','kpiAgreed','kpiEmergency','countOpen','quickFilters','clearFiltersBtn','resultSummary','dealRows','emptyState','detailEmpty','detailContent','detailClient','detailPhone','detailAddress','detailStage','detailManager','detailNextContact','detailNextTo','detailComment','openDealBtn','callBtn','scheduleBtn','callbackBtn','noanswerBtn','printBtn','completeBtn','objectLink','contactLink','scheduleDialog','scheduleForm','technicianSelect','visitDateTime','visitComment','cancelScheduleBtn','toast'].forEach(id=>E[id]=$(id));bind();init();});
function bind(){E.refreshBtn.onclick=()=>load(true);E.installBtn.onclick=install;E.searchInput.oninput=render;E.stageFilter.onchange=render;E.managerFilter.onchange=render;E.workTypeFilter.onchange=render;E.clearFiltersBtn.onclick=clear;E.newDealBtn.onclick=createDeal;E.quickFilters.onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;S.quick=b.dataset.filter;S.kpi=null;E.quickFilters.querySelectorAll('.quick-filter').forEach(x=>x.classList.toggle('is-active',x===b));render()};document.querySelectorAll('[data-quick-filter]').forEach(b=>b.onclick=()=>{S.kpi=S.kpi===b.dataset.quickFilter?null:b.dataset.quickFilter;render()});E.dealRows.onclick=e=>{const r=e.target.closest('tr[data-id]');if(r)select(r.dataset.id)};E.openDealBtn.onclick=openDeal;E.callBtn.onclick=call;E.scheduleBtn.onclick=openSchedule;E.callbackBtn.onclick=callback;E.noanswerBtn.onclick=noanswer;E.printBtn.onclick=printOrder;E.completeBtn.onclick=complete;E.scheduleForm.onsubmit=saveSchedule;E.cancelScheduleBtn.onclick=()=>E.scheduleDialog.close()}
function init(){if(!window.BX24||!BX24.init)return demo('Открыто вне Bitrix24');try{BX24.init(async()=>{S.mode='bitrix';S.domain=BX24.getDomain?BX24.getDomain():C.portal;badge('Подключено к Bitrix24','online');await load()});if(BX24.install)BX24.install(()=>{S.mode='bitrix';S.domain=BX24.getDomain?BX24.getDomain():C.portal;E.installBtn.classList.remove('is-hidden')})}catch(e){console.error(e);demo('Ошибка инициализации')}}
function demo(reason){S.mode='demo';badge('Демо: '+reason,'demo');S.stages=new Map([[C.s.new,'Просрочено ТО'],[C.s.planned,'Плановое ТО — согласование'],[C.s.callback,'Перезвон / думает'],[C.s.no1,'Недозвон / 1 и 2 касания'],[C.s.agreed,'Выезд согласован'],[C.s.legal,'Отказ / недопуск']]);S.users=new Map([['19','Верхоглазенко Т.И.'],['33','Алексеева И.Е.'],['31','Слесарь Петров А.А.'],['29','Слесарь Иванов Д.А.']]);[['Иванов Сергей Петрович','+7 900 111-22-33','г. Энгельс, ул. Тельмана, д. 10'],['Петрова Марина Викторовна','+7 900 222-33-44','п. Пробуждение, ул. Новая, д. 8'],['Смирнов Алексей Олегович','+7 900 333-44-55','п. Новопушкинское, ул. Советская, д. 30'],['Кузнецова Елена Игоревна','+7 900 444-55-66','п. Коминтерн, ул. Садовая, д. 4']].forEach((p,i)=>{const cid=String(50001+i);S.contacts.set(cid,{ID:cid,NAME:p[0],PHONE:[{VALUE:p[1]}]});S.deals.push({ID:String(40001+i),TITLE:'ВДГО: '+p[2],STAGE_ID:[C.s.new,C.s.planned,C.s.callback,C.s.agreed][i],CONTACT_ID:cid,ASSIGNED_BY_ID:i%2?'33':'19',[C.f.addr]:p[2],[C.f.visit]:i===3?new Date(Date.now()+14400000).toISOString():'',[C.f.nextContact]:i===2?new Date(Date.now()+86400000).toISOString():''})});fill();render();setKpis({today:1,overdue:4,noanswer:1,agreed:1,emergency:0})}
async function load(msg=false){if(S.mode!=='bitrix'||S.busy)return;busy(true);try{const [st,de]=await Promise.all([api('crm.status.list',{filter:{ENTITY_ID:'DEAL_STAGE_'+C.cat},order:{SORT:'ASC'}}),api('crm.deal.list',{order:{DATE_MODIFY:'DESC'},filter:{CATEGORY_ID:C.cat,'!STAGE_ID':[C.s.won,C.s.lose]},select:['ID','TITLE','STAGE_ID','CONTACT_ID','ASSIGNED_BY_ID','COMMENTS',...Object.values(C.f)],start:0})]);S.stages=new Map(st.map(x=>[x.STATUS_ID,x.NAME]));S.deals=de;const cids=[...new Set(de.map(x=>x.CONTACT_ID).filter(Boolean))],uids=[...new Set(de.flatMap(x=>[x.ASSIGNED_BY_ID,x[C.f.tech]]).filter(Boolean).map(String))];S.contacts.clear();S.users.clear();if(cids.length)(await api('crm.contact.list',{filter:{'@ID':cids},select:['ID','NAME','LAST_NAME','SECOND_NAME','PHONE'],start:0})).forEach(x=>S.contacts.set(String(x.ID),x));if(uids.length)(await api('user.get',{ID:uids})).forEach(x=>S.users.set(String(x.ID),name(x)));fill();render();await kpis();if(msg)toast('Данные обновлены.','success')}catch(e){console.error(e);badge('Ошибка обмена с Bitrix24','error');toast(e.message||'Ошибка загрузки','error')}finally{busy(false)}}
function fill(){const sv=E.stageFilter.value,mv=E.managerFilter.value;E.stageFilter.innerHTML='<option value="">Все рабочие стадии</option>'+[...S.stages].filter(([id])=>![C.s.won,C.s.lose].includes(id)).map(([id,n])=>`<option value="${h(id)}">${h(n)}</option>`).join('');E.stageFilter.value=sv;E.managerFilter.innerHTML='<option value="">Все диспетчеры</option>'+[...S.users].map(([id,n])=>`<option value="${h(id)}">${h(n)}</option>`).join('');E.managerFilter.value=mv;E.technicianSelect.innerHTML=[...S.users].map(([id,n])=>`<option value="${h(id)}">${h(n)}</option>`).join('')}
function render(){const q=E.searchInput.value.toLowerCase().trim(),st=E.stageFilter.value,m=E.managerFilter.value,w=E.workTypeFilter.value,now=new Date();const list=S.deals.filter(d=>{const c=S.contacts.get(String(d.CONTACT_ID)),text=[d.ID,d.TITLE,cname(c),phone(c),d[C.f.addr]].join(' ').toLowerCase();return(!q||text.includes(q))&&(!st||d.STAGE_ID===st)&&(!m||String(d.ASSIGNED_BY_ID)===m)&&(!w||String(d[C.f.work]||'')===w)&&quick(d,S.quick)&&(!S.kpi||kpimatch(d,S.kpi,now))});E.resultSummary.textContent=`Показано ${list.length} из ${S.deals.length}`;E.dealRows.innerHTML=list.map(row).join('');E.emptyState.classList.toggle('is-hidden',!!list.length);if(list.length&&!list.some(x=>String(x.ID)===String(S.selected)))select(list[0].ID,false);if(!list.length)detail(null)}
function row(d){const c=S.contacts.get(String(d.CONTACT_ID)),next=d[C.f.nextContact]||d[C.f.visit],sel=String(d.ID)===String(S.selected);return`<tr data-id="${h(d.ID)}" class="${sel?'is-selected':''}"><td>${h(d.ID)}</td><td><div class="cell-title">${h(cname(c)||d.TITLE||'Без названия')}</div><div class="cell-sub">${h(short(d.TITLE||'',60))}</div></td><td>${h(phone(c)||'—')}</td><td>${h(d[C.f.addr]||address(d.TITLE)||'—')}</td><td><span class="stage-pill ${stageClass(d.STAGE_ID)}">${h(S.stages.get(d.STAGE_ID)||d.STAGE_ID||'—')}</span></td><td>${h(S.users.get(String(d.ASSIGNED_BY_ID))||'#'+(d.ASSIGNED_BY_ID||'—'))}</td><td>${h(next?date(next):action(d[C.f.action])||'Не задано')}</td></tr>`}
function select(id,rer=true){S.selected=String(id);if(rer)render();detail(S.deals.find(x=>String(x.ID)===S.selected))}
function detail(d){if(!d){E.detailEmpty.classList.remove('is-hidden');E.detailContent.classList.add('is-hidden');return}const c=S.contacts.get(String(d.CONTACT_ID)),p=phone(c);E.detailEmpty.classList.add('is-hidden');E.detailContent.classList.remove('is-hidden');E.detailClient.textContent=cname(c)||d.TITLE||'Сделка #'+d.ID;E.detailPhone.innerHTML=p?`<a href="tel:${h(p.replace(/[^+\d]/g,''))}">${h(p)}</a>`:'—';E.detailAddress.textContent=d[C.f.addr]||address(d.TITLE)||'—';E.detailStage.textContent=S.stages.get(d.STAGE_ID)||d.STAGE_ID||'—';E.detailManager.textContent=S.users.get(String(d.ASSIGNED_BY_ID))||'#'+(d.ASSIGNED_BY_ID||'—');E.detailNextContact.textContent=date(d[C.f.nextContact])||'Не задан';E.detailNextTo.textContent=date(d[C.f.nextTo],true)||'Не задано';E.detailComment.textContent=strip(d[C.f.comment]||d.COMMENTS||'')||'—';link(E.objectLink,d[C.f.obj]);link(E.contactLink,d.CONTACT_ID?`https://${S.domain}/crm/contact/details/${d.CONTACT_ID}/`:null);E.callBtn.disabled=!p}
function quick(d,f){return f==='callback'?d.STAGE_ID===C.s.callback:f==='noanswer'?[C.s.no1,C.s.no3].includes(d.STAGE_ID):f==='planned'?d.STAGE_ID===C.s.planned:f==='agreed'?d.STAGE_ID===C.s.agreed:f==='legal'?d.STAGE_ID===C.s.legal:f==='manual'?d.STAGE_ID===C.s.manual:![C.s.won,C.s.lose].includes(d.STAGE_ID)}
function kpimatch(d,f,n){const v=parse(d[C.f.visit]),t=parse(d[C.f.nextTo]);return f==='today'?v&&same(v,n):f==='overdue'?t&&t<day(n):f==='noanswer'?[C.s.no1,C.s.no3].includes(d.STAGE_ID):f==='agreed'?d.STAGE_ID===C.s.agreed:f==='emergency'?String(d[C.f.work]||'')===C.e.emergency:true}
async function kpis(){const n=new Date(),a=day(n),b=new Date(a);b.setHours(23,59,59,999);const fs={today:{CATEGORY_ID:C.cat,['>='+C.f.visit]:a.toISOString(),['<='+C.f.visit]:b.toISOString()},overdue:{CATEGORY_ID:C.cat,['<'+C.f.nextTo]:a.toISOString(),'!STAGE_ID':[C.s.won,C.s.lose]},noanswer:{CATEGORY_ID:C.cat,STAGE_ID:[C.s.no1,C.s.no3]},agreed:{CATEGORY_ID:C.cat,STAGE_ID:C.s.agreed},emergency:{CATEGORY_ID:C.cat,[C.f.work]:C.e.emergency,'!STAGE_ID':[C.s.won,C.s.lose]}};const out={};for(const [k,f] of Object.entries(fs))out[k]=await total(f);setKpis(out)}
function setKpis(x){E.kpiToday.textContent=x.today;E.kpiOverdue.textContent=x.overdue;E.kpiNoanswer.textContent=x.noanswer;E.kpiAgreed.textContent=x.agreed;E.kpiEmergency.textContent=x.emergency;E.countOpen.textContent=S.deals.length>=50?'50+':S.deals.length}
function total(filter){return new Promise((res,rej)=>BX24.callMethod('crm.deal.list',{filter,select:['ID'],start:0},r=>r.error()?rej(new Error(r.error_description?r.error_description():r.error())):res(r.total?r.total():r.data().length)))}
function chosen(){return S.deals.find(x=>String(x.ID)===String(S.selected))}
function openDeal(){const d=chosen();if(d)window.open(`https://${S.domain}/crm/deal/details/${d.ID}/`,'_blank','noopener')}
function call(){const d=chosen(),p=phone(S.contacts.get(String(d&&d.CONTACT_ID)));if(p)location.href='tel:'+p.replace(/[^+\d]/g,'')}
function openSchedule(){if(!chosen())return;const d=new Date(Date.now()+3600000);d.setMinutes(Math.ceil(d.getMinutes()/30)*30,0,0);E.visitDateTime.value=local(d);E.visitComment.value='';E.scheduleDialog.showModal()}
async function saveSchedule(e){e.preventDefault();const d=chosen();if(!d)return;E.scheduleDialog.close();await update(d.ID,{STAGE_ID:C.s.agreed,[C.f.tech]:E.technicianSelect.value,[C.f.visit]:new Date(E.visitDateTime.value).toISOString(),[C.f.action]:C.e.visit,[C.f.comment]:E.visitComment.value.trim()},'Выезд назначен.')}
async function callback(){const d=chosen();if(!d)return;const v=prompt('Дата и время следующего звонка (ГГГГ-ММ-ДДTЧЧ:ММ)',local(new Date(Date.now()+86400000)));if(!v)return;const dt=new Date(v);if(isNaN(dt))return toast('Некорректная дата.','error');await update(d.ID,{STAGE_ID:C.s.callback,[C.f.action]:C.e.callback,[C.f.nextContact]:dt.toISOString()},'Перезвон запланирован.')}
async function noanswer(){const d=chosen();if(!d)return;await update(d.ID,{STAGE_ID:d.STAGE_ID===C.s.no1?C.s.no3:C.s.no1,[C.f.action]:C.e.callback,[C.f.nextContact]:new Date(Date.now()+86400000).toISOString()},'Недозвон зафиксирован.')}
async function complete(){const d=chosen();if(!d||!confirm('Отметить ТО выполненным и закрыть сделку?'))return;await update(d.ID,{STAGE_ID:C.s.won,[C.f.result]:C.e.completed,[C.f.done]:C.e.yes},'ТО выполнено.')}
async function update(id,fields,msg){if(S.mode==='demo'){Object.assign(S.deals.find(x=>String(x.ID)===String(id)),fields);toast(msg+' (демо)','success');render();return}busy(true);try{await api('crm.deal.update',{id,fields});toast(msg,'success');await load()}catch(e){toast(e.message,'error')}finally{busy(false)}}
async function createDeal(){if(S.mode==='demo')return toast('Создание доступно внутри Bitrix24.','error');const t=prompt('Название новой заявки');if(!t)return;try{const id=await api('crm.deal.add',{fields:{TITLE:t,CATEGORY_ID:C.cat,STAGE_ID:C.s.new}});toast('Создана заявка #'+id,'success');await load()}catch(e){toast(e.message,'error')}}
function printOrder(){const d=chosen();if(!d)return;const c=S.contacts.get(String(d.CONTACT_ID)),w=open('','_blank','width=900,height=750');if(!w)return toast('Разрешите всплывающие окна.','error');w.document.write(`<!doctype html><meta charset="utf-8"><title>ЗН #${h(d.ID)}</title><style>body{font:14px Arial;margin:35px}h1{text-align:center;font-size:20px}table{width:100%;border-collapse:collapse;margin:20px 0}td{border:1px solid;padding:8px}.box{height:180px;border:1px solid}.sign{display:grid;grid-template-columns:1fr 1fr;gap:60px;margin-top:70px}.line{border-top:1px solid;padding-top:5px}</style><h1>ЗАКАЗ-НАРЯД № ${h(d.ID)}</h1><table><tr><td><b>Заказчик</b></td><td>${h(cname(c)||'—')}</td></tr><tr><td><b>Телефон</b></td><td>${h(phone(c)||'—')}</td></tr><tr><td><b>Адрес</b></td><td>${h(d[C.f.addr]||address(d.TITLE)||'—')}</td></tr><tr><td><b>Дата выезда</b></td><td>${h(date(d[C.f.visit])||'________')}</td></tr><tr><td><b>Исполнитель</b></td><td>${h(S.users.get(String(d[C.f.tech]))||'________')}</td></tr><tr><td><b>Задание</b></td><td>${h(strip(d[C.f.comment]||d.COMMENTS||''))}</td></tr></table><p><b>Выполненные работы и замечания:</b></p><div class="box"></div><div class="sign"><div class="line">Исполнитель</div><div class="line">Заказчик</div></div><script>onload=()=>print()<\/script>`);w.document.close()}
function install(){if(S.mode!=='bitrix')return toast('Установка выполняется из локального приложения Bitrix24.','error');BX24.callMethod('placement.bind',{PLACEMENT:'LEFT_MENU',HANDLER:location.origin+location.pathname,TITLE:'Рабочий стол диспетчера',DESCRIPTION:'Заявки и выезды ВДГО',LANG_ALL:{ru:{TITLE:'Рабочий стол диспетчера',DESCRIPTION:'Заявки и выезды ВДГО'}}},r=>{if(r.error())return toast(r.error_description?r.error_description():r.error(),'error');if(BX24.installFinish)BX24.installFinish();E.installBtn.classList.add('is-hidden');toast('Пункт добавлен в левое меню.','success')})}
function api(method,params={}){return new Promise((res,rej)=>BX24.callMethod(method,params,r=>r.error()?rej(new Error(r.error_description?r.error_description():r.error())):res(r.data())))}
function clear(){E.searchInput.value=E.stageFilter.value=E.managerFilter.value=E.workTypeFilter.value='';S.quick='open';S.kpi=null;E.quickFilters.querySelectorAll('.quick-filter').forEach(x=>x.classList.toggle('is-active',x.dataset.filter==='open'));render()}
function busy(v){S.busy=v;document.querySelectorAll('button').forEach(b=>{if(b.id!=='cancelScheduleBtn')b.disabled=v});E.refreshBtn.textContent=v?'Загрузка…':'Обновить'}
function badge(t,k){E.connectionBadge.textContent=t;E.connectionBadge.className='connection-badge is-'+k}
function toast(t,k=''){E.toast.textContent=t;E.toast.className='toast'+(k?' is-'+k:'');clearTimeout(toast.tm);toast.tm=setTimeout(()=>E.toast.classList.add('is-hidden'),4200)}
function name(u){return[u.LAST_NAME,u.NAME,u.SECOND_NAME].filter(Boolean).join(' ')||'Сотрудник #'+u.ID}function cname(c){return c?[c.LAST_NAME,c.NAME,c.SECOND_NAME].filter(Boolean).join(' '):''}function phone(c){return c&&c.PHONE&&c.PHONE[0]?c.PHONE[0].VALUE:''}function link(e,v){e.href=v||'#';e.classList.toggle('is-disabled',!v||v==='#')}function address(t){return t&&t.includes('—')?t.split('—').slice(1).join('—').trim():''}function short(v,n){return v.length>n?v.slice(0,n-1)+'…':v}function strip(v){return String(v||'').replace(/\[\/?p\]/gi,'').replace(/<[^>]+>/g,'').trim()}function action(v){return({'10321':'Позвонить','10323':'Подготовить договор','10325':'Направить договор','10327':'Согласовать выезд','10329':'Выполнить выезд','10331':'Выставить счёт','10333':'Контроль оплаты','10335':'Повторный контакт'})[String(v||'')]||''}function stageClass(s){return[C.s.legal,C.s.lose].includes(s)?'is-danger':[C.s.no1,C.s.no3,C.s.callback].includes(s)?'is-warning':[C.s.agreed,C.s.won].includes(s)?'is-success':''}function parse(v){if(!v)return null;const d=new Date(v);return isNaN(d)?null:d}function date(v,only=false){const d=parse(v);return d?new Intl.DateTimeFormat('ru-RU',only?{dateStyle:'medium'}:{dateStyle:'short',timeStyle:'short'}).format(d):''}function local(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}function day(d){const x=new Date(d);x.setHours(0,0,0,0);return x}function same(a,b){return a.toDateString()===b.toDateString()}function h(v){return String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
})();
